version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the code...
      - BRANCH_NAME=$(echo $CODEBUILD_SOURCE_VERSION | cut -d '/' -f 3)
      - mkdir -p $BRANCH_NAME
      - find . -mindepth 1 -maxdepth 1 ! -name "$BRANCH_NAME" ! -name "SourceArti" -exec cp -r {} $BRANCH_NAME/ \;
artifacts:
  files:
    - '**/*'
  base-directory: $BRANCH_NAME